# BluePrintIQ Project Configuration
project:
  name: debug-test
  description: Debug test with enhanced logging
  type: architectural-specification
  version: "0.1.0"

# Architectural metadata
architecture:
  patterns: []
  technologies: []
  providers: []

# Specification settings
specifications:
  format: yaml
  validation: enabled
  auto_commit: true

# GitHub integration
github:
  auto_issues: true
  auto_project_board: true
  labels:
    - architecture
    - specification
    - blueprintiq

# Created by BluePrintIQ
metadata:
  created_at: 2025-07-16T09:39:31-07:00
  created_by: blueprintiq
  organization_id: test-org
  workspace_id: test-workspace
